import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Leftbar from "./components/UI/Leftbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex bg-red-400  items-stretch justify-between w-full h-full ">
          <div className="bg-yellow-400 grow-[2] hidden md:flex ">
            <Leftbar />
          </div>
          <div className="bg-zinc-400 grow-[3] lg:flex  lg:justify-between ">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
